{"name": "test_simple_assume[用例1]", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntest_fixture.py:47: AssumptionFailure\n>>\tpytest.assume(False)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               test_fixture.py:47: AssumptionFailure\nE               >>\tpytest.assume(False)\nE               AssertionError: assert False\n\n..\\venv\\lib\\site-packages\\six.py:702: FailedAssumption"}, "parameters": [{"name": "x", "value": "1"}, {"name": "y", "value": "1"}], "start": 1609831032970, "stop": 1609831032969, "uuid": "d95edefb-4313-44ed-9c8a-aeda27ce7b5f", "historyId": "76d008e295704d88114ae20ef35fdf5b", "testCaseId": "b14a107973ee251def56c625d5ba9ad0", "fullName": "test_fixture#test_simple_assume", "labels": [{"name": "suite", "value": "test_fixture"}, {"name": "host", "value": "jjiliu"}, {"name": "thread", "value": "43592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_fixture"}]}